version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/myapp
    depends_on:
      - mongodb
    volumes:
      - .:/app
    command: ["npm", "start"]
    restart: always

  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data: